"""Add delay_minutes to Project.

Revision ID: 2ad667bb4592
Revises: d9f75931a18
Create Date: 2013-02-26 19:29:57.882258

"""

# revision identifiers, used by Alembic.
revision = '2ad667bb4592'
down_revision = 'd9f75931a18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('delay_minutes', sa.Integer(),
                                       server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'delay_minutes')
    ### end Alembic commands ###
