"""Add is_locked field to testable.

Revision ID: 344c3f86394c
Revises: 15e554bd88aa
Create Date: 2013-10-14 21:02:27.239190

"""

# revision identifiers, used by Alembic.
revision = '344c3f86394c'
down_revision = '15e554bd88aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testable', sa.Column('is_locked', sa.Boolean(),
                                        server_default=u'0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testable', 'is_locked')
    ### end Alembic commands ###
