"""Add copy_to_execution field on FileVerifiers.

Revision ID: 41dda8349f27
Revises: 39a5823a808
Create Date: 2013-09-23 15:37:35.252101

"""

# revision identifiers, used by Alembic.
revision = '41dda8349f27'
down_revision = '39a5823a808'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileverifier', sa.Column('copy_to_execution', sa.Boolean(), server_default=u'0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fileverifier', 'copy_to_execution')
    ### end Alembic commands ###
