"""Add deadline field to project.

Revision ID: 15e554bd88aa
Revises: 32da2a33a6cc
Create Date: 2013-10-09 16:53:06.932851

"""

# revision identifiers, used by Alembic.
revision = '15e554bd88aa'
down_revision = '32da2a33a6cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('deadline', sa.DateTime(timezone=True),
                                       nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'deadline')
    ### end Alembic commands ###
