"""Add consent date field to user accounts.

Revision ID: 2a3f02244cb4
Revises: 32e8060589b8
Create Date: 2014-02-11 17:26:41.297088

"""

# revision identifiers, used by Alembic.
revision = '2a3f02244cb4'
down_revision = '32e8060589b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_user_consent_at', 'user', ['consent_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_consent_at', table_name='user')
    op.drop_column('user', 'consent_at')
    ### end Alembic commands ###
