"""Add is_hidden to Testable.

Revision ID: 525162a280bd
Revises: 305b60854a99
Create Date: 2013-10-28 16:35:44.615689

"""

# revision identifiers, used by Alembic.
revision = '525162a280bd'
down_revision = '305b60854a99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testable', sa.Column('is_hidden', sa.Boolean(),
                                        server_default=u'0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testable', 'is_hidden')
    ### end Alembic commands ###
